name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { ruby: ['3.2', '3.3'] }
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - run: bundle lock --add-platform x86_64-linux
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rubocop --force-exclusion
      - run: bundle exec rspec
